# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  cutils_config = debug
endif
ifeq ($(config),release)
  cutils_config = release
endif

PROJECTS := cutils

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

cutils:
ifneq (,$(cutils_config))
	@echo "==== Building cutils ($(cutils_config)) ===="
	@${MAKE} --no-print-directory -C . -f cutils.make config=$(cutils_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f cutils.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cutils"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"